"use client";

import { motion } from "framer-motion";

export function Hero() {
  return (
    <div className="relative w-full h-[50vh] min-h-[400px] flex items-center justify-center overflow-hidden">
      {/* Dynamic Background */}
      <div className="absolute inset-0 bg-black">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(0,242,254,0.15),transparent_50%)]" />
        <div className="absolute top-0 right-0 w-1/2 h-full bg-[radial-gradient(ellipse_at_center,rgba(139,92,246,0.1),transparent_50%)]" />
      </div>

      <div className="relative z-10 text-center px-4 max-w-4xl mx-auto flex flex-col items-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass text-neon-blue text-xs font-mono mb-6 border border-neon-blue/30"
        >
          <span className="w-2 h-2 rounded-full bg-neon-blue animate-pulse" />
          AI-GENERATED PREMIUM CINEMA
        </motion.div>
        
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2, ease: "easeOut" }}
          className="text-5xl md:text-7xl font-black tracking-tighter text-white mb-6 uppercase"
        >
          The Future of <br className="hidden md:block" />
          <span className="text-gradient">Storytelling</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4, ease: "easeOut" }}
          className="text-gray-400 text-lg md:text-xl max-w-2xl"
        >
          Curated collection of high-quality AI movies and dramas. 
          No shorts, just pure cinematic experiences generated by state-of-the-art AI.
        </motion.p>
      </div>

      {/* Fade out to content */}
      <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-black to-transparent" />
    </div>
  );
}
